// ReSharper disable InconsistentNaming

#nullable enable
using System;
using JetBrains.Annotations;
using Sirenix.OdinInspector;
using UnityEngine;
using UnityEngine.Assertions;
using UnityEngine.UI;
using Object = UnityEngine.Object;

namespace DG.Tweening
{
    public enum DOTweenAnimType : byte
    {
        None = 0,
        MoveY = 3,
        Move = 2,
        Rotate = 4,
        Scale = 5,
        Color = 6,
        Fade = 7,
        PunchPos = 9,
        PunchRot = 10,
        PunchScale = 11,
        ShakePos = 12,
        ShakeRot = 13,
        ShakeScale = 14,
        UIAnchors = 22,
    }

    /// <summary>
    /// Attach this to a GameObject to create a tween
    /// </summary>
    public sealed class DOTweenAnim : MonoBehaviour
#if UNITY_EDITOR
        , ISelfValidator
#endif
    {
        [NonSerialized]
        public Tweener? tween;

        public float delay;
        [MinValue(0.0001f)]
        public float duration = 1;
        public Ease easeType = Ease.OutQuad;
        public AnimationCurve easeCurve = new(new Keyframe(0, 0), new Keyframe(1, 1));
        public LoopType loopType = LoopType.Restart;
        public int loops = 1;
        public bool isRelative = true;
        public bool isFrom;
        public bool autoKill = true;
        public bool autoGenerate = true; // If TRUE automatically creates the tween at startup

        [Required, ChildGameObjectsOnly]
        public Component target = null!;
        public DOTweenAnimType animationType;
        public bool autoPlay = true;

        public float endValueFloat;
        public Vector3 endValueV3;
        public Color endValueColor = new Color(1, 1, 1, 1);

        public bool optionalBool0, optionalBool1;
        public float optionalFloat0;
        public int optionalInt0;

        private bool _tweenAutoGenerationCalled; // TRUE after the tweens have been autoGenerated

        #region Unity Methods

        private void Awake()
        {
            if (!autoGenerate) return;

            PopulateTween(play: autoPlay);
            _tweenAutoGenerationCalled = true;
        }

        private void Start()
        {
            if (_tweenAutoGenerationCalled || !autoGenerate) return;

            PopulateTween(play: autoPlay);
            _tweenAutoGenerationCalled = true;
        }

        private void OnDestroy()
        {
            if (tween != null)
            {
                if (tween.active)
                    tween.Kill();
                tween = null;
            }
        }

        // Used also by DOTweenAnimationInspector when applying runtime changes and restarting
        /// <summary>
        /// Creates the tween manually (called automatically if AutoGenerate is set in the Inspector)
        /// from its target's current value.
        /// </summary>
        /// <param name="play">If TRUE also plays the tween, otherwise only creates it</param>
        public Tweener PopulateTween(bool play)
        {
            Assert.AreNotEqual(DOTweenAnimType.None, animationType, "AnimationType is None");
            Assert.IsNotNull(target, "Target is null");

            if (tween is not { active: true })
            {
                tween = CreateTween(play: play);
                tween.OnKill(() => tween = null);
            }

            return tween;
        }

        [MustUseReturnValue]
        public Tweener CreateTween(bool play)
        {
            L.I($"[DOTweenAnimation] CreateTween: {animationType} - {target}", this);

            // Create tween.
            var t = CreateTween(
                target, transform, animationType, duration,
                endValueFloat, endValueV3, endValueColor,
                optionalBool0, optionalBool1, optionalFloat0, optionalInt0);

            // Set from or relative.
            if (isFrom) t.From(isRelative);
            else t.SetRelative(isRelative);

            // Set basic tween settings.
            t.SetTarget(gameObject)
                .SetDelay(delay).SetLoops(loops, loopType).SetAutoKill(autoKill);

            // Set easeType.
            if (easeType is Ease.INTERNAL_Custom) t.SetEase(easeCurve);
            else t.SetEase(easeType);

            if (play is false) t.Pause();
            return t;
        }

        #endregion

        private static Tweener CreateTween(
            Object target, Transform transform,
            DOTweenAnimType animType,
            float duration,
            float endValueFloat,
            Vector3 endValueV3,
            Color endValueColor,
            bool optionalBool0,
            bool optionalBool1,
            float optionalFloat0,
            int optionalInt0)
        {
            Assert.IsTrue(duration > 0, "Duration must be greater than 0");

            return animType switch
            {
                DOTweenAnimType.MoveY => transform.DOLocalMoveY(endValueV3.y, duration),
                DOTweenAnimType.Move => transform.DOLocalMove(endValueV3, duration),
                DOTweenAnimType.Rotate => transform.DOLocalRotateZ(endValueV3.z, duration),
                DOTweenAnimType.Scale => transform.DOScale(optionalBool0 ? new Vector3(endValueFloat, endValueFloat, endValueFloat) : endValueV3, duration),
                DOTweenAnimType.Color => target switch
                {
                    Graphic t => t.DOColor(endValueColor, duration),
                    SpriteRenderer t => t.DOColor(endValueColor, duration),
                    Renderer t => t.material.DOColor(endValueColor, duration),
                    _ => throw new ArgumentOutOfRangeException(nameof(target), target, null)
                },
                DOTweenAnimType.Fade => target switch
                {
                    CanvasGroup t => t.DOFade(endValueFloat, duration),
                    Graphic t => t.DOFade(endValueFloat, duration),
                    SpriteRenderer t => t.DOFade(endValueFloat, duration),
                    Renderer t => t.material.DOFade(endValueFloat, duration),
                    _ => throw new ArgumentOutOfRangeException(nameof(target), target, null)
                },
                DOTweenAnimType.PunchPos => target switch
                {
                    RectTransform t => t.DOPunchAnchorPos(endValueV3, duration, optionalInt0, optionalFloat0),
                    Transform t => t.DOPunchPosition(endValueV3, duration, optionalInt0, optionalFloat0),
                    _ => throw new ArgumentOutOfRangeException(nameof(target), target, null)
                },
                DOTweenAnimType.PunchScale => transform.DOPunchScale(endValueV3, duration, optionalInt0, optionalFloat0),
                DOTweenAnimType.PunchRot => transform.DOPunchRotation(endValueV3, duration, optionalInt0, optionalFloat0),
                DOTweenAnimType.ShakePos => target switch
                {
                    RectTransform t => t.DOShakeAnchorPos(duration, endValueV3, optionalInt0, optionalFloat0, optionalBool1),
                    Transform t => t.DOShakePosition(duration, endValueV3, optionalInt0, optionalFloat0, optionalBool1),
                    _ => throw new ArgumentOutOfRangeException(nameof(target), target, null)
                },
                DOTweenAnimType.ShakeScale => transform.DOShakeScale(duration, endValueV3, optionalInt0, optionalFloat0, optionalBool1),
                DOTweenAnimType.ShakeRot => transform.DOShakeRotation(duration, endValueV3, optionalInt0, optionalFloat0, optionalBool1),
                DOTweenAnimType.UIAnchors => DOTween.To(() => ((RectTransform) target).anchorMin, x => ((RectTransform) target).anchorMin = ((RectTransform) target).anchorMax = x, (Vector2) endValueV3, duration),
                _ => throw new ArgumentOutOfRangeException(nameof(animType), animType, null)
            };
        }

#if UNITY_EDITOR
        void ISelfValidator.Validate(SelfValidationResult result)
        {
            if (animationType is DOTweenAnimType.None)
                result.AddError("AnimationType must be set to a valid value");

            if (animationType
                is DOTweenAnimType.Move
                or DOTweenAnimType.PunchPos
                or DOTweenAnimType.ShakePos)
            {
                if (optionalBool0)
                    result.AddError("Snapping is not supported anymore.");
            }

            if (animationType is DOTweenAnimType.Rotate)
            {
                if (endValueV3.x != 0 || endValueV3.y != 0)
                    result.AddError("Rotate can only rotate on the Z axis");
                if (isRelative is false)
                    result.AddError("Rotate must be relative. Otherwise, it would result unexpected rotation.");
            }

            if (animationType
                is DOTweenAnimType.PunchPos
                or DOTweenAnimType.PunchRot
                or DOTweenAnimType.PunchScale)
            {
                if (easeType is not Ease.OutQuad)
                    result.AddError("Punch must use OutQuad ease type.");
                if (isFrom)
                    result.AddError("Punch cannot be from.");
            }

            if (animationType
                is DOTweenAnimType.ShakePos
                or DOTweenAnimType.ShakeRot
                or DOTweenAnimType.ShakeScale)
            {
                if (easeType is not Ease.Linear)
                    result.AddError("Shake must use Linear ease type.");
                if (isFrom)
                    result.AddError("Shake cannot be from.");
            }

            if (animationType
                is DOTweenAnimType.Fade
                or DOTweenAnimType.Color
                or DOTweenAnimType.PunchPos
                or DOTweenAnimType.PunchRot
                or DOTweenAnimType.PunchScale
                or DOTweenAnimType.ShakePos
                or DOTweenAnimType.ShakeRot
                or DOTweenAnimType.ShakeScale
                or DOTweenAnimType.UIAnchors)
            {
                if (isRelative)
                    result.AddError(animationType + " cannot be relative.");
            }
        }
#endif
    }
}